#!/usr/bin/python

import os, sys
from concordion.runners import FolderRunner

if len(sys.argv) != 2:
    print "USAGE :", sys.argv[0], "tests_directory"
    sys.exit(1)

directory = sys.argv[1]
FolderRunner().run(directory)
