#!/usr/bin/python

import os, sys
from optparse import OptionParser

parser = OptionParser(
	usage="USAGE: %prog [options] SOURCE_FOLDER", 
	version="0.6.0",
	description="Run all the pyConcordion tests contained in OUTPUT_FOLDER and sub folders."	
)
parser.add_option("-o", "--output_folder", 
                  help="generate report in OUTPUT_FOLDER", metavar="OUTPUT_FOLDER")

(options, args) = parser.parse_args()
if len(args) != 1:
	parser.error("incorrect number of arguments")
real_options = {}
if options.output_folder is not None:
	real_options['output_folder'] = options.output_folder

from concordion.runners import FolderRunner
FolderRunner().run(args[0], real_options)
